// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PIMBackend.DTOs;

namespace PIMBackend.Migrations
{
    [DbContext(typeof(PIMContext))]
    partial class PIMContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PIMBackend.DTOs.Employee", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(19,0)")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("BIRTH_DATE");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("FIRST_NAME");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("LAST_NAME");

                    b.Property<decimal>("Version")
                        .HasColumnType("numeric(10,0)")
                        .HasColumnName("VERSION");

                    b.Property<string>("Visa")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasColumnName("VISA")
                        .IsFixedLength(true);

                    b.HasKey("Id");

                    b.ToTable("EMPLOYEE");
                });

            modelBuilder.Entity("PIMBackend.DTOs.Group", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(19,0)")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("GroupLeaderId")
                        .HasColumnType("numeric(19,0)")
                        .HasColumnName("GROUP_LEADER_ID");

                    b.Property<decimal>("Version")
                        .HasColumnType("numeric(10,0)")
                        .HasColumnName("VERSION");

                    b.HasKey("Id");

                    b.HasIndex("GroupLeaderId")
                        .IsUnique();

                    b.ToTable("GROUP");
                });

            modelBuilder.Entity("PIMBackend.DTOs.Project", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(19,0)")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CUSTOMER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("END_DATE");

                    b.Property<decimal>("GroupId")
                        .HasColumnType("numeric(19,0)")
                        .HasColumnName("GROUP_ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NAME");

                    b.Property<decimal>("ProjectNumber")
                        .HasColumnType("numeric(4,0)")
                        .HasColumnName("PROJECT_NUMBER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("START_DATE");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasColumnName("STATUS")
                        .IsFixedLength(true);

                    b.Property<decimal>("Version")
                        .HasColumnType("numeric(10,0)")
                        .HasColumnName("VERSION");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex(new[] { "ProjectNumber" }, "UQ__PROJECT__C11D06095E954A32")
                        .IsUnique();

                    b.ToTable("PROJECT");
                });

            modelBuilder.Entity("PIMBackend.DTOs.ProjectEmployee", b =>
                {
                    b.Property<decimal>("ProjectId")
                        .HasColumnType("numeric(19,0)")
                        .HasColumnName("PROJECT_ID");

                    b.Property<decimal>("EmployeeId")
                        .HasColumnType("numeric(19,0)")
                        .HasColumnName("EMPLOYEE_ID");

                    b.HasKey("ProjectId", "EmployeeId")
                        .HasName("PK__PROJECT___1F22B372CF8BB702");

                    b.HasIndex("EmployeeId");

                    b.ToTable("PROJECT_EMPLOYEE");
                });

            modelBuilder.Entity("PIMBackend.DTOs.Group", b =>
                {
                    b.HasOne("PIMBackend.DTOs.Employee", "GroupLeader")
                        .WithOne("Groups")
                        .HasForeignKey("PIMBackend.DTOs.Group", "GroupLeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupLeader");
                });

            modelBuilder.Entity("PIMBackend.DTOs.Project", b =>
                {
                    b.HasOne("PIMBackend.DTOs.Group", "Group")
                        .WithMany("Projects")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("FK__PROJECT__GROUP_I__2A4B4B5E")
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("PIMBackend.DTOs.ProjectEmployee", b =>
                {
                    b.HasOne("PIMBackend.DTOs.Employee", "Employee")
                        .WithMany("ProjectEmployees")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("FK__PROJECT_E__EMPLO__300424B4")
                        .IsRequired();

                    b.HasOne("PIMBackend.DTOs.Project", "Project")
                        .WithMany("ProjectEmployees")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("FK__PROJECT_E__PROJE__2F10007B")
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PIMBackend.DTOs.Employee", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("ProjectEmployees");
                });

            modelBuilder.Entity("PIMBackend.DTOs.Group", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("PIMBackend.DTOs.Project", b =>
                {
                    b.Navigation("ProjectEmployees");
                });
#pragma warning restore 612, 618
        }
    }
}
